In [ ]:
!pip install torch

# Credits

This is heavily based on https://github.com/pytorch/tutorials

# What is PyTorch?

> **NOTE** In the last part of this lab cuda is used. If you have a cuda enabled machine, read the README.md in the root of this repo on how to use nvidia-docker.


It’s a Python based scientific computing package targeted at two sets of
audiences:
-  A replacement for numpy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed


# Getting Started

In this lab you will get a quick start on what pytorch is and how to use it.

## 1. Tensors

Tensors are similar to numpy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

In [4]:
import torch
torch.cuda.is_available()

False

Construct a 5x3 matrix, uninitialized

In [7]:
x = torch.Tensor(5, 3)
print(x)

tensor([[-1.2629e-29,  1.1393e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


Construct a randomly initialized matrix

In [10]:
x = torch.rand(5, 3)
print(x)

tensor([[0.4974, 0.0558, 0.9820],
        [0.7789, 0.8038, 0.9549],
        [0.5674, 0.6771, 0.9916],
        [0.6055, 0.2714, 0.3667],
        [0.7509, 0.3925, 0.7063]])


Get its size

In [13]:
print(x.size())

torch.Size([5, 3])


**NOTE**: `torch.Size` is in fact a tuple, so it supports the same operations that a tuple supports.

In [16]:
x[1:3] = 2
print(x)

tensor([[0.4974, 0.0558, 0.9820],
        [2.0000, 2.0000, 2.0000],
        [2.0000, 2.0000, 2.0000],
        [0.6055, 0.2714, 0.3667],
        [0.7509, 0.3925, 0.7063]])


# Assignment

Make use of the pytorch docs <http://pytorch.org/docs/torch>
1. Make a tensor of size (2, 17)
2. Make a torch.FloatTensor of size (3, 1)
3. Make a torch.LongTensor of size (5, 2, 1)
  - fill the entire tensor with 7s
4. Make a torch.ByteTensor of size (5,)
  - fill the middle 3 indices with ones such that it records [0, 1, 1, 1, 0]

## _Solution 1_

In [20]:
t = torch.Tensor(2, 17)
print(t)

tensor([[-1.2918e-29,  1.1393e-42,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00]])


## _Solution 2_

In [23]:
t = torch.FloatTensor(3, 1)
print(t)

tensor([[-1.2724e-29],
        [ 1.1393e-42],
        [ 0.0000e+00]])


## _Solution 3_

In [28]:
base = torch.LongTensor(5, 2, 1)
base.fill_(7)
print(base)

tensor([[[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]]])


## *Solution 4*

In [61]:
base = torch.ByteTensor(5)
base.zero_()
base[1:4] = 1
print(base)

tensor([0, 1, 1, 1, 0], dtype=torch.uint8)


## 2. Operations
There are multiple syntaxes for operations. Let's see addition as an example:

### 2.1 Addition: syntax 1

In [64]:
y = torch.rand(5, 3)
print(x + y)

tensor([[1.4522, 0.5209, 1.2065],
        [2.1564, 2.2543, 2.8008],
        [2.0743, 2.2922, 2.1060],
        [0.8884, 0.5349, 0.7147],
        [1.4850, 1.3882, 1.5809]])


### 2.2 Addition: syntax 2

In [67]:
print(torch.add(x, y))

tensor([[1.4522, 0.5209, 1.2065],
        [2.1564, 2.2543, 2.8008],
        [2.0743, 2.2922, 2.1060],
        [0.8884, 0.5349, 0.7147],
        [1.4850, 1.3882, 1.5809]])


### 2.3 Addition: giving an output tensor

In [70]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[1.4522, 0.5209, 1.2065],
        [2.1564, 2.2543, 2.8008],
        [2.0743, 2.2922, 2.1060],
        [0.8884, 0.5349, 0.7147],
        [1.4850, 1.3882, 1.5809]])


### 2.4 Addition: in-place

adds `x`to `y`

In [73]:
y.add_(x)
print(y)

tensor([[1.4522, 0.5209, 1.2065],
        [2.1564, 2.2543, 2.8008],
        [2.0743, 2.2922, 2.1060],
        [0.8884, 0.5349, 0.7147],
        [1.4850, 1.3882, 1.5809]])


**NOTE**: Any operation that mutates a tensor in-place is post-fixed with an `_`. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

You can use standard numpy-like indexing with all bells and whistles!

In [77]:
print(x[:, 1])

tensor([0.0558, 2.0000, 2.0000, 0.2714, 0.3925])


**Read later** 100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc are described here <http://pytorch.org/docs/torch>

# Assignment

1. multiplication of two tensors (see [torch.Tensor.mul](http://pytorch.org/docs/master/tensors.html#torch.Tensor.mul))
2. do the same, but inplace
3. division of two tensors (see [torch.Tensor.div](http://pytorch.org/docs/master/tensors.html#torch.Tensor.div))
4. perform a matrix multiplication of two tensors of size (2, 4) and (4, 2)

## *Solution 1*

In [92]:
a = torch.Tensor([1, 2, 3])
b = torch.Tensor([4, 5, 6])
result_1 = torch.mul(a, b)
print(result_1)
res = a * b
print(res)

tensor([ 4., 10., 18.])
tensor([ 4., 10., 18.])


## *Solution 2*

In [95]:
a.mul_(b)
print(a)

tensor([ 4., 10., 18.])


## *Solution 3*

In [98]:
a = torch.Tensor([1, 2, 3])
b = torch.Tensor([4, 5, 6])
res = torch.div(a, b)
print(res)

tensor([0.2500, 0.4000, 0.5000])


## *Solution 4*

In [105]:
a = torch.Tensor(2, 4)
b = torch.Tensor(4, 2)

a.fill_(1)
b.fill_(2)

result = torch.mm(a, b)
print(result)

tensor([[8., 8.],
        [8., 8.]])


## 3. Numpy Bridge

Converting a torch Tensor to a numpy array and vice versa is a breeze.

The torch Tensor and numpy array will share their underlying memory locations, and changing one will change the other.

### 3.1 Converting torch Tensor to numpy Array

In [108]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [110]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value: the `numpy()` method provides a *view* of the original tensor, not a copy.

In [113]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### 3.2 Converting numpy Array to torch Tensor

See how changing the np array changed the torch Tensor automatically

In [116]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# Assignment

1. create a tensor of size (5, 2) containing ones
2. now convert it to a numpy array
3. now convert it back to a torch tensor

## *Solution 1*

In [119]:
t = torch.ones(5, 2)
print(t)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])


## *Solution 2*

In [124]:
n = t.numpy()
print(n)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


## *Solution 3*

In [128]:
t_again = torch.from_numpy(n)
print(t_again)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])


All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

## 4 CUDA Tensors

Tensors can be moved onto GPU using the `.cuda` function.
This is not necessary, but check the `README.md` for details on how to use a GPU with docker.

In [ ]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    z = x + y
    # Notice that the tensors are now of type torch.cuda.FloatTensor (notice the cuda in there)
    # This is meant as a tensor to be run on the GPU.
    # The .cuda() does this to any parameter it is applied to.
    print(x)
    print(y)
    print(z)
else:
    print("CUDA not available on your machine.")


### 
$$
_This won't be done now_
$$
